apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-depl
  namespace: mkx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ordering
  template:
    metadata:
      labels:
        app: ordering
    spec:
      containers:
      - name: ordering-container
        image: 148761635844.dkr.ecr.ap-northeast-2.amazonaws.com/mkx/ordering:latest
        ports:
        - containerPort: 8080
        # 아래의 name과 application.yml의 ${}의 변수명과 일치해야함
        env:
        - name: DB_PASSWORD_2
          valueFrom:
            secretKeyRef:
              name: mkx-secrets
              key: DB_PASSWORD_2
        - name: DB_HOST_2
          valueFrom:
            secretKeyRef:
              name: mkx-secrets
              key: DB_HOST_2
        - name: DB_PORT_2
          valueFrom:
            secretKeyRef:
              name: mkx-secrets
              key: DB_PORT_2
        - name: REDIS_CLUSTER_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: mkx-secrets
              key: REDIS_CLUSTER_ENDPOINT
        # 컨테이너 상태 확인을 통해 롤링업데이트 최적화 
        readinessProbe:
          httpGet:
            # healthcheck 경로
            path: /health
            port: 8080
          # 컨테이너 시작 후 지연
          initialDelaySeconds: 10
          # 확인 반복 주기
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: ordering-service
  namespace: mkx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ordering