apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data-pvc
  namespace: mkx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3  # gp2 → gp3로 변경 (빠르고 저렴)
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-config-pvc
  namespace: mkx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3  # gp2 → gp3로 변경
  resources:
    requests:
      storage: 1Gi