apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-depl
  namespace: mkx
spec:
  replicas: 2  # HPA 초기값
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway-container
        image: 148761635844.dkr.ecr.ap-northeast-2.amazonaws.com/mkx/api-gateway:latest
        ports:
        - containerPort: 8080
        # 리소스 설정 (HPA 필수)
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        # 아래의 name과 application.yml의 ${}의 변수명과 일치해야함
        env:
        - name: JWT_SECRET_AT
          valueFrom:
            secretKeyRef:
              name: mkx-secrets
              key: JWT_SECRET_AT
        - name: JWT_SECRET_RT
          valueFrom:
            secretKeyRef:
              name: mkx-secrets
              key: JWT_SECRET_RT
        # 컨테이너 상태 확인을 통해 롤링업데이트 최적화 
        readinessProbe:
          httpGet:
            # healthcheck 경로
            path: /health
            port: 8080
          # 컨테이너 시작 후 지연
          initialDelaySeconds: 10
          # 확인 반복 주기
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: mkx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: api-gateway