package com.beyond.MKX.domain.delisting.entity;

import com.beyond.MKX.common.domain.BaseIdAndTimeEntity;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Comment;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * 분기별 제출 서류 관리 엔티티
 * 
 * 상장사가 분기별로 제출해야 하는 재무제표, 감사보고서, 사업보고서 등의
 * 제출 현황과 검토 과정을 체계적으로 관리합니다.
 * 제출 지연 시 상장폐지 절차의 중요한 기준이 됩니다.
 *
 */
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
@Entity
@Table(name = "quarterly_submissions",
       indexes = {
           @Index(name = "idx_quarterly_sub_stock_year_quarter", columnList = "stock_id, fiscal_year, fiscal_quarter"),
           @Index(name = "idx_quarterly_sub_type", columnList = "submission_type"),
           @Index(name = "idx_quarterly_sub_status", columnList = "submission_status"),
           @Index(name = "idx_quarterly_sub_deadline", columnList = "deadline_date"),
           @Index(name = "idx_quarterly_sub_submitted", columnList = "submitted_at")
       })
@Comment("분기별 제출 서류 관리")
public class QuarterlySubmission extends BaseIdAndTimeEntity {

    /**
     * 제출 주식 ID
     * 어떤 주식의 제출 서류인지 식별
     */
    @Column(name = "stock_id", nullable = false)
    @Comment("제출 주식 ID")
    private UUID stockId;

    /**
     * 회계 연도
     * 해당 제출 서류의 회계 연도
     */
    @Column(name = "fiscal_year", nullable = false)
    @Comment("회계 연도")
    private int fiscalYear;

    /**
     * 회계 분기
     * 1분기(1), 2분기(2), 3분기(3), 4분기(4), 연간(null)
     */
    @Column(name = "fiscal_quarter")
    @Comment("회계 분기")
    private Integer fiscalQuarter;

    /**
     * 제출 서류 유형
     * FINANCIAL_STATEMENT: 재무제표, AUDIT_REPORT: 감사보고서, 
     * BUSINESS_REPORT: 사업보고서, QUARTERLY_REPORT: 분기보고서
     */
    @Column(name = "submission_type", nullable = false, length = 30)
    @Enumerated(EnumType.STRING)
    @Comment("제출 서류 유형")
    private SubmissionType submissionType;

    /**
     * 제출 상태
     * PENDING: 대기, SUBMITTED: 제출완료, UNDER_REVIEW: 검토중,
     * APPROVED: 승인, REJECTED: 반려, OVERDUE: 제출지연
     */
    @Column(name = "submission_status", nullable = false, length = 20)
    @Enumerated(EnumType.STRING)
    @Comment("제출 상태")
    private SubmissionStatus submissionStatus = SubmissionStatus.PENDING;

    /**
     * 제출 마감일
     * 해당 서류의 제출 마감일시
     */
    @Column(name = "deadline_date", nullable = false)
    @Comment("제출 마감일")
    private LocalDateTime deadlineDate;

    /**
     * 실제 제출일시
     * 서류가 실제로 제출된 시점 (null: 미제출)
     */
    @Column(name = "submitted_at")
    @Comment("실제 제출일시")
    private LocalDateTime submittedAt;

    /**
     * 제출자 ID
     * 서류를 제출한 담당자 (기업 관리자)
     */
    @Column(name = "submitted_by")
    @Comment("제출자 ID")
    private UUID submittedBy;

    /**
     * 승인일시
     * 서류가 승인된 시점 (null: 미승인)
     */
    @Column(name = "approved_at")
    @Comment("승인일시")
    private LocalDateTime approvedAt;

    /**
     * 검토자 ID
     * 서류를 검토한 관리자
     */
    @Column(name = "reviewer_id")
    @Comment("검토자 ID")
    private UUID reviewerId;

    /**
     * 검토 의견
     * 검토자가 작성한 의견이나 코멘트
     */
    @Column(name = "review_comment", columnDefinition = "TEXT")
    @Comment("검토 의견")
    private String reviewComment;

    /**
     * 제출 파일 URL
     * 실제 제출된 파일의 저장 위치
     */
    @Column(name = "file_url")
    @Comment("제출 파일 URL")
    private String fileUrl;

    /**
     * 파일 크기 (바이트)
     * 제출된 파일의 크기
     */
    @Column(name = "file_size")
    @Comment("파일 크기 (바이트)")
    private Long fileSize;

    /**
     * 파일 해시값
     * 파일 무결성 검증을 위한 해시값
     */
    @Column(name = "file_hash", length = 64)
    @Comment("파일 해시값")
    private String fileHash;

    /**
     * 제출 지연 일수
     * 마감일 대비 지연된 일수 (음수: 조기제출)
     */
    @Column(name = "delay_days")
    @Comment("제출 지연 일수")
    private Integer delayDays;

    /**
     * 반려 사유
     * 서류가 반려된 경우의 구체적인 사유
     */
    @Column(name = "rejection_reason", columnDefinition = "TEXT")
    @Comment("반려 사유")
    private String rejectionReason;

    /**
     * 재제출 횟수
     * 반려 후 재제출한 횟수
     */
    @Column(name = "resubmission_count")
    @Comment("재제출 횟수")
    private Integer resubmissionCount = 0;

    /**
     * 긴급 제출 여부
     * 마감일 임박으로 긴급 제출된 경우
     */
    @Column(name = "is_urgent")
    @Comment("긴급 제출 여부")
    private Boolean isUrgent = false;

    /**
     * 자동 생성 여부
     * 시스템에 의해 자동으로 생성된 제출 요청인지 여부
     */
    @Column(name = "is_auto_generated")
    @Comment("자동 생성 여부")
    private Boolean isAutoGenerated = false;

    /**
     * 동시성 제어(낙관적 락)
     */
    @Version
    @Column(name = "version", nullable = false)
    private long version;
}