version: '3.8'

services:
  # ---------- Kafka (단일 KRaft) ----------
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"  # 내부 접근용 (Docker 네트워크 내)
      - "9094:9094"  # 외부 접근용 (로컬 앱 접속용)
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://:9092,PLAINTEXT_EXTERNAL://:9094,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:9092,PLAINTEXT_EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 4
      KAFKA_LOG_RETENTION_HOURS: 168
    #    volumes:
    #      - mkx-kafka-data:/tmp/kraft-combined-logs
    restart: unless-stopped
    networks: [app-net]


  # ---------- 카프카 소스 커넥터(Debezium) ----------
  connect:
    image: quay.io/debezium/connect:2.7
    container_name: kafka-connect
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: mkx-connect-cluster
      CONFIG_STORAGE_TOPIC: _mkx_connect_configs
      OFFSET_STORAGE_TOPIC: _mkx_connect_offsets
      STATUS_STORAGE_TOPIC: _mkx_connect_status
      # ----------------------------------------------------

      # --- 그 외의 설정들은 CONNECT_ 접두사를 사용 ---
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_ERRORS_TOLERANCE: all
      CONNECT_ERRORS_DEADLETTERQUEUE_TOPIC_NAME: _mkx_connect_dlq
      CONNECT_ERRORS_DEADLETTERQUEUE_CONTEXT_HEADERS_ENABLE: "true"
      CONNECT_ERRORS_LOG_ENABLE: "true"
    networks: [ app-net ]



  # ---------- Redis Cluster (오더북 전용: 3노드) ----------
  redis-node-1:
    image: redis:7.2
    container_name: redis-node-1
    command: ["redis-server",
              "--port", "7001",
              "--cluster-enabled", "yes",
              "--cluster-config-file", "/data/nodes.conf",
              "--appendonly", "yes",
              "--dir", "/data",
              "--cluster-announce-ip", "redis-node-1",
              "--cluster-announce-hostname", "localhost",
              "--cluster-announce-port", "7001",
              "--cluster-announce-bus-port", "17001"]
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
      - mkx-redis-node-1-data:/data
    restart: unless-stopped
    networks: [app-net]

  redis-node-2:
    image: redis:7.2
    container_name: redis-node-2
    command: ["redis-server",
              "--port", "7002",
              "--cluster-enabled", "yes",
              "--cluster-config-file", "/data/nodes.conf",
              "--appendonly", "yes",
              "--dir", "/data",
              "--cluster-announce-ip", "redis-node-2",
              "--cluster-announce-hostname", "localhost",
              "--cluster-announce-port", "7002",
              "--cluster-announce-bus-port", "17002"]
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - mkx-redis-node-2-data:/data
    restart: unless-stopped
    networks: [app-net]

  redis-node-3:
    image: redis:7.2
    container_name: redis-node-3
    command: ["redis-server",
              "--port", "7003",
              "--cluster-enabled", "yes",
              "--cluster-config-file", "/data/nodes.conf",
              "--appendonly", "yes",
              "--dir", "/data",
              "--cluster-announce-ip", "redis-node-3",
              "--cluster-announce-hostname", "localhost",
              "--cluster-announce-port", "7003",
              "--cluster-announce-bus-port", "17003"]
    ports:
      - "7003:7003"
      - "17003:17003"
    volumes:
      - mkx-redis-node-3-data:/data
    restart: unless-stopped
    networks: [app-net]
  # 클러스터 최초 1회 구성:
  # docker exec -it redis-node-1 redis-cli --cluster create redis-node-1:7001 redis-node-2:7002 redis-node-3:7003 --cluster-replicas 0


  # ---------- MKX-Redis (공통 캐시/세션/키밸류) ----------
  mkx-redis:
    image: redis:7.2
    container_name: mkx-redis
    command: ["redis-server", "--appendonly", "yes", "--dir", "/data", "--save", "60", "1"]
    ports:
      - "6380:6379"
    volumes:
      - mkx-common-redis-data:/data
    restart: unless-stopped
    networks: [app-net]

  # ---------- MariaDB ----------
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: mkx_platform
      MARIADB_CHARACTER_SET_SERVER: utf8mb4
      MARIADB_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3309:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mkx-mariadb-data:/var/lib/mysql
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      # 필요하면 초기 스키마/데이터:
      # - ./initdb.d:/docker-entrypoint-initdb.d:ro
    networks: [app-net]

  # ---------- InfluxDB (시계열 데이터 저장소) ----------
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ORG: MKX
      DOCKER_INFLUXDB_INIT_BUCKET: MKX_MarketData
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 5-Sgev2iZAFZW-rxiedi6dN0c7cA5_pDFzcNuj65BINx0Q_21yYwSF1MquMEaQrY2dwzir6aL9vrdCkCWu2B4w==
    volumes:
      - mkx-influxdb-data:/var/lib/influxdb2
      - mkx-influxdb-config:/etc/influxdb2
    restart: unless-stopped
    networks: [app-net]



networks:
  app-net:
    driver: bridge

volumes:
  #  mkx-kafka-data:
  mkx-redis-node-1-data:
  mkx-redis-node-2-data:
  mkx-redis-node-3-data:
  mkx-common-redis-data:
  mkx-mariadb-data:
  mkx-influxdb-data:
  mkx-influxdb-config: