apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-bot-depl
  namespace: mkx
spec:
  replicas: 1  # 고정 (중복 실행 방지)
  selector:
    matchLabels:
      app: trading-bot
  template:
    metadata:
      labels:
        app: trading-bot
    spec:
      containers:
      - name: trading-bot-container
        image: 148761635844.dkr.ecr.ap-northeast-2.amazonaws.com/mkx/trading-bot:latest
        ports:
        - containerPort: 8080
          name: http
        # 리소스 설정 (고정 레플리카)
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: DB_HOST_1
          valueFrom:
            secretKeyRef:
              name: mkx-secrets
              key: DB_HOST_1
        - name: DB_PASSWORD_1
          valueFrom:
            secretKeyRef:
              name: mkx-secrets
              key: DB_PASSWORD_1
        - name: DB_PORT_1
          valueFrom:
            secretKeyRef:
              name: mkx-secrets
              key: DB_PORT_1
        readinessProbe:
          httpGet:
            # healthcheck 경로
            path: /health
            port: 8080
          # 컨테이너 시작 후 지연
          initialDelaySeconds: 10
          # 확인 반복 주기
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: trading-bot-service
  namespace: mkx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: trading-bot